# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.01.24
_src_path: gh:scientific-python/cookie
backend: hatch
email: raymond.ehlers@cern.ch
full_name: Raymond Ehlers
license: BSD
org: raymondEhlers
project_name: pachyderm
project_short_description: Physics Analysis Core for Heavy-Ions
url: https://github.com/raymondEhlers/pachyderm
vcs: true
