---
repos:
    - repo: "https://gitlab.com/pycqa/flake8"
      rev: 3.7.9  # 3.6.0 doesn't contain this configuration file.
      hooks:
          - id: flake8
            additional_dependencies: ["flake8-colors"]
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.20.0
      hooks:
          - id: yamllint
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.770
      hooks:
          - id: mypy
            # no-incremental helps with a bug in ruamel.yaml typing.
            # See: https://sourceforge.net/p/ruamel-yaml/tickets/328/
            args: ["--ignore-missing-imports", "--no-incremental"]
            # A sufficiently new version of attrs is needed to keep mypy happy.
            # Same with ruamel.yaml
            additional_dependencies: ["attrs>=19.3.0", "ruamel.yaml>=0.16.10"]
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.5.1
      hooks:
          - id: python-check-mock-methods
          - id: rst-backticks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
          - id: trailing-whitespace
          - id: check-executables-have-shebangs
    - repo: https://github.com/asottile/seed-isort-config
      rev: v2.1.0
      hooks:
          - id: seed-isort-config
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.21
      hooks:
          - id: isort
            additional_dependencies: ["toml"]
