---
repos:
    - repo: "https://gitlab.com/pycqa/flake8"
      rev: 3.9.2  # 3.6.0 doesn't contain this configuration file.
      hooks:
          - id: flake8
            additional_dependencies: ["flake8-colors"]
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.26.1
      hooks:
          - id: yamllint
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.910
      hooks:
          - id: mypy
            # no-incremental helps with a bug in ruamel.yaml typing.
            # See: https://sourceforge.net/p/ruamel-yaml/tickets/328/
            args: ["--ignore-missing-imports", "--no-incremental"]
            # A sufficiently new version of attrs is needed to keep mypy happy.
            # Same with ruamel.yaml
            additional_dependencies: ["attrs>=19.3.0", "ruamel.yaml>=0.16.10", "numpy>=1.21"]
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0
      hooks:
          - id: python-check-mock-methods
          - id: rst-backticks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-added-large-files
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-case-conflict
          - id: check-symlinks
          - id: check-yaml
          - id: mixed-line-ending
          - id: trailing-whitespace
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.9.2
      hooks:
          - id: isort
            additional_dependencies: ["toml"]
    - repo: https://github.com/python/black
      rev: 21.6b0
      hooks:
          - id: black
            language_version: python3.7
