[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pachyderm"
description = "Physics Analysis Core for Heavy-Ions"
readme = "README.md"
license = "BSD-3-Clause"
requires-python = ">=3.8"
keywords = [
    "HEP",
    "ALICE",
]
authors = [
  { name = "Raymond Ehlers", email = "raymond.ehlers@cern.ch" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
]
dynamic = ["version"]
include = [
    "pachyderm/py.typed",
    "pachyderm/alice/datasets/*.yaml",
]
dependencies = [
    "attrs >=21.2.0",
    "numpy >=1.21",
    "scipy >=1.7.0",
    "matplotlib >=3.3.2",
    "iminuit >=2.7.0",
    "numdifftools >=0.9.40",
    "ruamel.yaml >=0.17.10",
]

[project.optional-dependencies]
docs = [
    "Sphinx >=4.0.3",
    "recommonmark >=0.7.1",
    "sphinx-markdown-tables >=0.0.15",
    "importlib-metadata >=4.6.1",
]
dev = [
    "uproot >=4",
    "pre-commit >=2.13.0",
    "flake8 >=3.9.2",
    "flake8-colors >=0.1.6",
    "mypy >=0.931",
    "pytest >=6.2.4",
    "pytest-cov >=2.12.1",
    "pytest-mock >=3.6.1",
    "codecov >=2.1.11",
    "boost-histogram >=1.2.1",
    "black >=22.1.0",
    "isort >= 5.10",
]

[project.scripts]
downloadALICEDataset = "pachyderm.alice.download:run_dataset_download"
downloadALICERunByRun = "pachyderm.alice.download:run_download_run_by_run_train_output"

[tool.hatch]
version.path = "src/pachyderm/__init__.py"

[tool.mypy]
files = "src"
python_version = "3.7"
warn_unused_configs = true
strict = true
show_error_codes = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]
warn_unreachable = true

[tool.black]
line-length = 120
target-version = ["py36"]

[tool.isort]
profile = "black"
line_length = 120
skip = ["docs/conf.py"]
skip_glob = ".*"

[tool.pylint]
master.py-version = "3.7"
master.ignore-paths= ["src/pachyderm/_version.py"]
reports.output-format = "colorized"
similarities.ignore-imports = "yes"
messages_control.disable = [
  "design",
  "fixme",
  "line-too-long",
  "wrong-import-position",
]
