[tool.poetry]
name = "pachyderm"
version = "3.0"
description = "Physics Analysis Core for Heavy-Ions"
authors = ["Raymond Ehlers <raymond.ehlers@cern.ch>"]
license = "BSD-3-Clause"
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
]
keywords = [
    "HEP",
    "ALICE",
]
include = [
    "pachyderm/py.typed",
    "pachyderm/alice/datasets/*.yaml",
]

[tool.poetry.scripts]
downloadALICEDataset = "pachyderm.alice.download:run_dataset_download"
downloadALICERunByRun = "pachyderm.alice.download:run_download_run_by_run_train_output"

[tool.poetry.dependencies]
python = "^3.6.1"
attrs = ">=19.3.0"
numpy = "^1.19.3"
scipy = "^1.5.3"
matplotlib = "^3.3.2"
iminuit = "^1.5.2"
numdifftools = "^0.9.39"
"ruamel.yaml" = "^0.16.12"
dataclasses = {version = "^0.7", python="^3.6, <3.7"}
importlib-resources = {version = "^3.3.0", python="^3.6, <3.7"}
# These are the docs requirements. Ideally, I would put them into the dev docs.
# However, pep517 won't install the dev dependencies.
# So we move it here to enable building the docs, even though it's a bit of a waste...
Sphinx = {version = "^3.2.1", optional = true}
recommonmark = "^0.7.1"
sphinx-markdown-tables = {version = "^0.0.15", optional = true}
importlib-metadata = "^3.4.0"

[tool.poetry.extras]
docs = ["Sphinx", "recommonmark", "sphinx-markdown-tables", "importlib-metadata"]

[tool.poetry.dev-dependencies]
uproot = "^4.0.1"
pre-commit = "^2.8.2"
flake8 = "^3.8.4"
flake8-colors = "^0.1.6"
mypy = "^0.800"
isort = {extras = ["toml"], version = "^5.6.4"}
pytest = "^6.2.1"
pytest-cov = "^2.11.1"
pytest-mock = "^3.5.1"
codecov = "^2.1.11"
boost-histogram = {version = "^0.11.1", optional = true}
black = "^20.8b1"

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
lines_after_imports = 2
verbose = true
skip = ["docs/conf.py"]
skip_glob = ".*"

[tool.black]
line-length = 120
target-version = ["py36"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
