[tool.poetry]
name = "pachyderm"
version = "3.0"
description = "Physics Analysis Core for Heavy-Ions"
authors = ["Raymond Ehlers <raymond.ehlers@cern.ch>"]
license = "BSD-3-Clause"
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
]
keywords = [
    "HEP",
    "ALICE",
]
include = [
    "pachyderm/py.typed",
    "pachyderm/alice/datasets/*.yaml",
]

[tool.poetry.scripts]
downloadALICEDataset = "pachyderm.alice.download:run_dataset_download"
downloadALICERunByRun = "pachyderm.alice.download:run_download_run_by_run_train_output"

[tool.poetry.dependencies]
python = "^3.6,^3.7"
attrs = ">=19.3.0"
numpy = "^1.19.3"
scipy = "^1.5.3"
matplotlib = "^3.3.2"
iminuit = "^1.5.2"
numdifftools = "^0.9.39"
"ruamel.yaml" = "^0.16.12"
dataclasses = {version = "^0.7", python="^3.6.1, <3.7"}
importlib-resources = {version = "^3.3.0", python="^3.6.1, <3.7"}

[tool.poetry.dev-dependencies]
uproot4 = "^0.1.0"
pre-commit = "^2.8.2"
flake8 = "^3.8.4"
flake8-colors = "^0.1.6"
mypy = "^0.790"
isort = {extras = ["toml"], version = "^5.6.4"}
seed-isort-config = "^2.2.0"
pytest = "^6.1.2"
pytest-cov = "^2.10.1"
pytest-mock = "^3.3.1"
codecov = "^2.1.10"
Sphinx = "^3.2.1"
recommonmark = "^0.6.0"
sphinx-markdown-tables = "^0.0.15"
importlib-metadata = {version = "^2.0.0", python="^3.6.1, <3.8"}

[tool.isort]
known_standard_library = ["setuptools", "typing_extensions"]
known_third_party = ["attr", "iminuit", "matplotlib", "numdifftools", "numpy", "pytest", "ruamel", "scipy", "uproot4"]
known_first_party = []
line_length = 120
# Meaning a grouped grid of imports
multi_line_output = 3
lines_after_imports = 2
force_grid_wrap = 0
use_parentheses = true
include_trailing_comma = true
verbose = true
skip = ["docs/conf.py"]
skip_glob = ".*"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
